{"name": "Тест заранее проваленный у авторизованного пользователя", "status": "skipped", "statusDetails": {"message": "XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be", "trace": "E   AssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be"}, "description": "Открываем страницу товара \n        Добавляем товар в корзину \n        Проверяем, что нет сообщения об успехе с помощью is_not_element_present", "attachments": [{"name": "stdout", "source": "4a9829e4-557f-431f-b426-1e301b9482bf-attachment.txt", "type": "text/plain"}], "start": 1745139468239, "stop": 1745139470457, "uuid": "40a0064b-8540-4af5-a7f6-f669808e6744", "historyId": "30c605defbf4742efa95810519bfab7a", "testCaseId": "30c605defbf4742efa95810519bfab7a", "fullName": "tests.ui.test_product_page.TestUserAddToBasketFromProductPage#test_user_cant_see_success_message_after_adding_product_to_basket", "labels": [{"name": "story", "value": "Product Feature"}, {"name": "feature", "value": "Product"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Now not work!')"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_product_page"}, {"name": "subSuite", "value": "TestUserAddToBasketFromProductPage"}, {"name": "host", "value": "c045dde3dc68"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_product_page"}]}