{"name": "Тест заранее проваленный у авторизованного пользователя", "status": "skipped", "statusDetails": {"message": "XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be", "trace": "E   AssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be"}, "description": "Открываем страницу товара \n        Добавляем товар в корзину \n        Проверяем, что нет сообщения об успехе с помощью is_not_element_present", "attachments": [{"name": "stdout", "source": "32605a81-5e68-4a58-9870-e2e54d2bf410-attachment.txt", "type": "text/plain"}], "start": 1745140478651, "stop": 1745140480453, "uuid": "97fb8b33-b824-47a6-9e65-62c5e9ffef69", "historyId": "30c605defbf4742efa95810519bfab7a", "testCaseId": "30c605defbf4742efa95810519bfab7a", "fullName": "tests.ui.test_product_page.TestUserAddToBasketFromProductPage#test_user_cant_see_success_message_after_adding_product_to_basket", "labels": [{"name": "story", "value": "Product Feature"}, {"name": "feature", "value": "Product"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Now not work!')"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_product_page"}, {"name": "subSuite", "value": "TestUserAddToBasketFromProductPage"}, {"name": "host", "value": "b9d88d75dd9b"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_product_page"}]}